### ISSUE TITLE
Buttons not registering on Kona 'Hit the tricks they call out', might be a case with others also.

### ISSUE THREAD

**Issue by jayshai** [PARTYMANX/partymod-thps4#10]
Having issues with the buttons not registering once called out. Tried all of them and none seem to work. Works on College fine.

![Screenshot 2023-12-21 123745](https://github.com/PARTYMANX/partymod-thps4/assets/18117157/01b130eb-6f50-4696-bc76-1f9537800cd1)

**Comment by PARTYMANX** [comment]
Those tricks must be done with a spine transfer over the ramp's center spine in the combo

**Comment by jayshai** [comment]
You're right, my bad lol.
