### ISSUE TITLE
can't apply the patch to the nocd exe

### ISSUE THREAD

**Issue by robertesaum** [PARTYMANX/partymod-thps4#5]
I'm using a version of the nocd executable, and I can't patch it, only the original version of the exe, but I don't have a CD driver on my computer, so I can't play the game. :(

**Comment by PARTYMANX** [comment]
open a cmd window in the game directory (type `cmd` into the address bar of file explorer), then run the patcher like so:
`partypatcher.exe -f`
that forces the patch to be applied if the executable is of the right size

**Comment by buvk** [comment]
On a similar note, is it possible to make it so that THPS4 is portable and does not need to be installed?  If it is not installed, I get the following errors:

"Tony Hawk's Pro Skater 4 was unable to initialize graphics engine."
"Tony Hawk's Pro Skater 4 has exited because the serial number is not valid.  Try reinstalling the software."

Maybe the serial number could be specified via partyconfig?

**Comment by PARTYMANX** [comment]
I strictly avoid touching any copy protection code. it's probably too risky, even it puts different different copy protection in its place.  The DMCA pretty specifically calls out removing copy protection.  sucks but unless Microsoft/Activision were to tell me I can, I'm not touching it

**Comment by robertesaum** [comment]
> open a cmd window in the game directory (type `cmd` into the address bar of file explorer), then run the patcher like so: `partypatcher.exe -f` that forces the patch to be applied if the executable is of the right size

Worked perfectly! Thank you very much, excellent work.

**Comment by ks202005** [comment]
> open a cmd window in the game directory (type `cmd` into the address bar of file explorer), then run the patcher like so: `partypatcher.exe -f` that forces the patch to be applied if the executable is of the right size

This also works for me using the Razor1911 patch with the md5 checksum of `a73fecec9a5e6f50226c1110912ca1be`. Thanks!

As per the partypatcher.exe notes, here are the CRCs:

```
INPUT CRC DOES NOT MATCH EXPECTED: 3c92df41
OUTPUT CRC DOES NOT MATCH EXPECTED: 8705ebb8
```

**Comment by PARTYMANX** [comment]
added the relevant checksums to the patcher now
