### ISSUE TITLE
Keep getting 'Please insert disk' everytime I go to apply a skill point

### ISSUE THREAD

**Issue by jayshai** [PARTYMANX/partymod-thps4#8]
Hi,

I'm using your patch and a NOCD crack but when I go to apply a skill point, this pops up. If I click retry it dissapears and allows me to continue but do you have a solution or specific crack I should use for this patch that doesn't have this issue?

![Screenshot 2023-12-18 183802](https://github.com/PARTYMANX/partymod-thps4/assets/18117157/d87dabe6-dcef-4a72-bb16-9f70de774598)

Cheers :)

**Comment by jordanshaikly** [comment]
Found a better crack that doesn't seem to have this issue.

**Comment by PARTYMANX** [comment]
Sadly, I cannot help you with this.  All I can say is that this seems to be related to improper installs of the game.  I've seen others run into the issue and if I recall uninstalling the game entirely and reinstalling worked.

**Comment by jayshai** [comment]
Thanks for suggesting, it looks like the CD2 didn't copy the 'PlayDiskStart.exe' over to the main game directory which seems to be the cause of why this issue was showing. Added this along with the data (movies) files and all seems good now 👍

**Comment by cheatfreak47** [comment]
bit of an odd bump but in case anyone wants to know the actual solution for this problem, since neither of those problems fix the issue: 

this is really just a result of the most common nocd having a missed cd check patch

The thpsx community discord has the proper nocd if anyone cares
