### ISSUE TITLE
Way to implement Controller vibration when let go off 'A' and when bumping into wall like the Xbox version?

### ISSUE THREAD

**Issue by jayshai** [PARTYMANX/partymod-thps4#9]
The xbox version has it so whenever you jump, the controller vibrates slightly and also when bumping into walls.

Is there a way to implement this into the PC version?

Thanks

**Comment by PARTYMANX** [comment]
that was something I was curious about... the game only ever seems to act like there's one actuator in the controller, which doesn't seem like correct behavior.  perhaps my code is going wrong somewhere.  I would think that the vibration should be the exact same as the xbox release, being that the pc version is based on it.

**Comment by jayshai** [comment]
Yeah, I've never been able to get any of DirectInput to Xinput drivers to work with this game so unable to test if this was once a possibility with this game on PC. I have played it on Xemu and the vibration is there but I assume the code for that is stored in the Xbox executable and would be strange for them to remove it but then again, controller support for PC wasn't as popular back then.

**Comment by PARTYMANX** [comment]
Sure enough, I investigated for a bit over lunch and this is a bug, and it's a weird one!  

It's just like the friction bug where you can see it's supposed to work how you expected, but somewhere along the line there's a bug in floating point calculations where certain things are dropped.  I think it's a compiler bug.  I was always curious if it only affected friction...

I reimplemented the function that actually sets the actuators and now it works as I figured it should work (small vibrations when doing a manual is the one that sticks out to me).  I'll get that released later today.

**Comment by jayshai** [comment]
Legend, thanks for looking into that. Looking forward to when its released :)

**Comment by jayshai** [comment]
I've just found another bug I believe. When doing two player mode, Player 1 will feel controller vibration for both player 1 and 2 and Player 2 will feel no controller vibration. Should I create a new ticket for this?

**Comment by PARTYMANX** [comment]
No need, I found and corrected that while investigating this one.  Turns out the device object is passed in with a 4 byte offset to the actuator setting function.  weird.

**Comment by PARTYMANX** [comment]
New release includes the fix

**Comment by jayshai** [comment]
Thanks all seems good except the jump vibration seems very weak / almost unnoticeable in comparison to the Xbox version. Is this just how its intended?

**Comment by PARTYMANX** [comment]
You're totally right, I completely missed that they reverse the left and right inputs to the actuation function.  Will have that fixed very soon

**Comment by jayshai** [comment]
Nice one, thanks. 

No relation but thought I'd mention that the net.qb from the Level Expansion pack (that was made a while back that was never finished) updated the text from 'GameSpy Arcade' to 'Online' in the Network Play menu. 

Here's the file if you want to implement it into the patcher at some point as obviously GameSpys defunct so keeps the UI more up to date:

[net.qb.zip](https://github.com/PARTYMANX/partymod-thps4/files/13746853/net.qb.zip)

**Comment by PARTYMANX** [comment]
Fixed!  

I avoid making changes like that to modernize stuff.  Also I just like that there's a bit of a hint as to why there's no server browser
